try {
    let number = 5;
    let result = number * 2;
    console.log(result);
} catch (error) {
    console.log('Something went wrong');
}
